### ISSUE TITLE
Tags and skillmodels.__version__

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/skillmodels#43]
## Goal

We want to be able to find the skillmodels version by typing `skillmodels.__version__` and checkout the corresponding source code via a tag. 

## Proposed implementation

Use [`zest.releaser`](https://pypi.org/project/zest.releaser/) to do the tagging and handling of the version number. I don't think it will completely replace our `release.py` because I didn't see any conda integration. My preferred solution would be to still have one python skript like `release.py` with a few additional command line arguments.

Since this will be relevant for respy, estimagic, gettsim and skillmodels, maybe someone else could look into it and then help me to implement it in skillmodels and estimagic.

@hmgaudecker, @tobiasraabe feel free to comment.

**Comment by tobiasraabe** [comment]
Some bigger projects (e.g. pandas) use https://github.com/warner/python-versioneer, but I do not understand what it exactly does by skimming the readme.

There is also https://github.com/c4urself/bump2version. I used the parent project a lot and it is probably the slimmest of all options.

**Comment by hmgaudecker** [comment]
> Some bigger projects (e.g. pandas) use https://github.com/warner/python-versioneer, but I do not understand what it exactly does by skimming the readme.

Last commit to the repo 2 years ago. Have not tried looking through the 107 forks, but this does not seem like an active project.


> Use [`zest.releaser`](https://pypi.org/project/zest.releaser/) to do the tagging and handling of the version

> There is also https://github.com/c4urself/bump2version. I used the parent project a lot and it is probably the slimmest of all options.

I would be fine with any of the two -- both seem to be reasonably active and do what they are supposed to do. If @tobiasraabe has experience with bump[2]version, that probably is the most useful option given that we want to set it up and forget about it.

**Comment by janosg** [comment]
Yes, bump2version should be sufficient.

**Comment by tobiasraabe** [comment]
I also fine with it. I am writing a maintenance guide for gettsim and document bump2version. Then, you can use it as well.

**Comment by hmgaudecker** [comment]
Outdated.
